version: "3.9"

services:

  nodeapp:
    image: 127.0.0.1:5000/nodeapp
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 15s
    ports:
      - "3000:3000"
    build:
      context: .
      args:
        NODE_ENV: production
    command: ["npm", "run", "start"]
